spring:
    data:
        mongodb:
            host: ds035613.mlab.com
            port: 35613
            database: lab-arsw7
            username: arsw
            password: Arsw123
    redis:
        host: 192.168.56.101
        port: 6379
        #password: